services:
  document-intelligence:
    build: .
    container_name: adobe-hackathon-pipeline
    volumes:
      # Mount local directories to Docker container paths
      - ./app/input:/app/input
      - ./app/output:/app/output
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: python src/main.py 